### ISSUE TITLE
Formatting on transfer LP page (mobile)

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/Basilisk-ui#295]
Whoops!

![image](https://user-images.githubusercontent.com/97540577/216969533-60971ce5-9b44-4c8b-9b52-da0b6394870f.png)

![image](https://user-images.githubusercontent.com/97540577/216971293-18c2073d-1591-4e67-b5c4-8cd9389376a8.png)

**Comment by joseJRJR** [comment]
Also when transfer others assets, not only LP

And like see above other UI displaced
![Screenshot_2023-02-06-10-24-40-250_io novafoundation nova market](https://user-images.githubusercontent.com/123791232/216996879-2b032c5e-ae92-4e8c-b1af-bfcc6fec9cfa.jpg)
