### ISSUE TITLE
"Show all assets" button not working

### ISSUE THREAD

**Issue by green-jay** [galacticcouncil/Basilisk-ui#300]
Steps to reproduce:
Basilisk Rococo testnet -> Wallet page -> click on "Show all assets"

Expected:
All assets from the asset registry are shown.

Actual:
Only owned assets are shown in both active and inactive button state.

**Comment by jak-pan** [comment]
> Steps to reproduce: Basilisk Rococo testnet -> Wallet page -> click on "Show all assets"
> 
> Expected: All assets from the asset registry are shown.
> 
> Actual: Only owned assets are shown in both active and inactive button state.

To add to this. Only assets that have metadata pre-filled. Is that fine for your use? @green-jay
