### ISSUE TITLE
Medium size display pools screen styling

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/Basilisk-ui#305]
<img width="840" alt="Screenshot 2023-02-08 at 15 29 29" src="https://user-images.githubusercontent.com/3409250/217562507-4d2ffba3-5af3-4445-9cb8-378b2b16651f.png">

**Comment by vkulinich-cl** [comment]
@jak-pan do you have a design or ideas how we could solve this? Show mobile view or move those buttons to another place or idk?

**Comment by jak-pan** [comment]
> @jak-pan do you have a design or ideas how we could solve this? Show mobile view or move those buttons to another place or idk?

I think flip to mobile is good. We were also working on tile view I'll try to look it up. basically using mobile tiles with fixed-width range for more compact view

**Comment by jak-pan** [comment]
How hard would this be? https://www.figma.com/file/HZt2Xm6sfGWsI3vnnnaMC9/%F0%9F%96%A5--Basilisk-v0.5-%7C-Desktop?node-id=12433%3A155349&t=6MguIsxeQyZ0fZ9O-4

**Comment by jak-pan** [comment]
@DuriSK we probably don't have logic for this right? It seems like it's not finished unfortunately. 

In that case I'd just flip mobile view but this would be really coool

**Comment by vkulinich-cl** [comment]
> 

The pool card from the link already exists. We just need to combine them and create a view shown on the figma

**Comment by jak-pan** [comment]
It does but the flow is probably not completely compatible with desktop so we might leave this for later. As quickfix I'd flip to mobile while we complete the tiles view. (If you quickly test it tho I wouldn't protest to see if it works if it's like 30 min thing)
