### ISSUE TITLE
My positions switch on pools page not working

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/Basilisk-ui#307]
<img width="972" alt="Screenshot 2023-02-09 at 00 11 14" src="https://user-images.githubusercontent.com/3409250/217672717-0786910d-d838-4f76-ac57-cec6995bea9f.png">

reproducible on https://beta-app.basilisk.cloud

**Comment by vkulinich-cl** [comment]
@jak-pan how should it work in this case? I don't have any positions and I see nothing in my case.

**Comment by jak-pan** [comment]
It should show the no positions screen if there are no positions but I do have position and it's missing (you can see by total value in pools)

**Comment by jak-pan** [comment]
To be more specific KSM/BSX position and I can see it normally while the filter is not on.

**Comment by jak-pan** [comment]
https://www.figma.com/file/HZt2Xm6sfGWsI3vnnnaMC9/%F0%9F%96%A5--Basilisk-v0.5-%7C-Desktop?node-id=10954%3A143109&t=6MguIsxeQyZ0fZ9O-1 here is the no-positions screen + we can adjust wording while we're at it
