### ISSUE TITLE
Improve 

### ISSUE THREAD

**Issue by weihao900301** [galacticcouncil/Basilisk-ui#791]
No notification of transaction results

### Detailed Description
Every time a transaction is converted, there is no prompt result, and it is unknown whether it is successful.Interaction options re-turned to interactable green。

### Context
No success notification was received during use, and the account balance feedback was not timely，Misleading me to think that it needs to be confirmed again, and inexplicably repeated the interaction many times.
After the improvement, users can clearly understand the transaction results and avoid mistakes and repeat operations.

### Possible Implementation
I think there can be a pop-up window or a transaction progress prompt after the transaction is confirmed.

If there is a reward, please send it to the wallet address below
my wallet address：5Hb26dgUF4dVjsnucgzGUZXuQ8PubEvKxdk91YcUeb7NbuPk

**Comment by mamunptsc** [comment]
Very good performance polkadot dex

But swap time very long
Plz short this time

My address: bXmAXpUN88v6A8wirwFGcKtPpbbrtodhjuztTstBqgiFx1oft
