### ISSUE TITLE
Tokens visibility 

### ISSUE THREAD

**Issue by ozziigor** [galacticcouncil/Basilisk-ui#961]
Can't see tokens in my wallet other than BSX

### Detailed Description

When I open my account on https://testnet-app.bsx.fi/ I can't see other tokens on it after i made trades

### Context

Good for accounting purposes 

Good for accounting purposes

**Comment by Cubo25** [comment]
Closing this issue hence we are already in production and this functionality has been tested and works properly.

Please try : https://app.basilisk.cloud/#/wallet 

Thanks
